### ISSUE TITLE
How do you actually measure yours performance and those ops/sec ?

### ISSUE THREAD

**Issue by solarfrantz** [debut-js/Indicators#10]

**Comment by BusinessDuck** [comment]
This assessment is subjective and depends on the performance of the environment, but the [benchmark](https://github.com/debut-js/indicators-benchmark) that we use in runs and evaluates different libraries in the same environment. This allows you to estimate the ratio of performance within a single run. The number of operations per second may differ in real use up or down.

**Comment by solarfrantz** [comment]
Thanks for clarification, I've discovered later the other repo. Issue can be closed.
