### ISSUE TITLE
FEATURE: Parabolic SAR

### ISSUE THREAD

**Issue by sivo1981** [debut-js/Indicators#11]
I just love your indicators. Any chance of adding Parabolic SAR to the collection?

**Comment by BusinessDuck** [comment]
i have no time yet, i am focused on the main platform Debut, but pSAR its base as well, i think later it will be added to project

**Comment by sivo1981** [comment]
> i have no time yet, i am focused on the main platform Debut, but pSAR its base as well, i think later it will be added to project

Great to hear that. If i have some time, maybe i can make an PR.

**Comment by BusinessDuck** [comment]
> > i have no time yet, i am focused on the main platform Debut, but pSAR its base as well, i think later it will be added to project
> 
> 
> 
> Great to hear that. If i have some time, maybe i can make an PR.

Sure, i can review that, you should know a few important things before make a PR.
1. It would be nice to have excel (spreadsheet) calculations to compare results and write unit with excel data
2. If it's possible write units and compare tests for cross library, to verify results with technical indicators
3. Prevent use reduce, and any loops, that's performance bottlenecks

**Comment by BusinessDuck** [comment]
Get excel tables for psar from here: https://tradingtuitions.com/parabolic-sar-trading-system-intraday-live-signals-and-excel-sheet/

**Comment by StaRenn** [comment]
https://github.com/debut-js/Indicators/pull/12

**Comment by BusinessDuck** [comment]
> #12

merged
