### ISSUE TITLE
ATR sometimes return undefined value

### ISSUE THREAD

**Issue by buuni** [debut-js/Indicators#25]
###  Problem:
If the same `low`, `close` and `high` values are passed to the ATR indicator, the result will be `undefined`.

```js
const atr = new ATR(14)
const result = atr.nextvalue(10, 10, 10) // undefined
```
### Potential Solve:
This is due to the fact that you need to do a check after getting the result of the work `getTrueRange` on `trueRange === null` because value is `0` its normal result, but `getTrueRange` return null only if not provided `prevClose` argument

https://github.com/debut-js/Indicators/blob/master/src/atr.ts#L42

**Comment by BusinessDuck** [comment]
PR with fixes is done
