### ISSUE TITLE
I can't calculate in case realtime

### ISSUE THREAD

**Issue by dearvn** [debut-js/Indicators#33]
Hi admin,

I try to use your indicators, everything is good but when I run it on websocket and I want to get sma in 5minutes, there are a lot of CLOSE value in 5m and your indicator is wrong maybe it push new value to buffer instead on update last value in last element in buffer.

Please help review your indicator when run on websocket.

Thanks.

**Comment by BusinessDuck** [comment]
HI! Sorry for long time delay with answer.

When you use a socket, it may contain price data, not candles. The indicator takes a closed bar as an argument to the nextValue function. Provide an example of data from a socket

**Comment by BusinessDuck** [comment]
Any other questions? Can i close the issue?

**Comment by BusinessDuck** [comment]
Closed by inactivity
