### ISSUE TITLE
Trendlines

### ISSUE THREAD

**Issue by emorling** [debut-js/Indicators#43]
Thanks for providing this excellent package!
I noticed that you have a sub-project in a folder for trend lines. 
What is the status, since you didnt include it in the description of this project?
Are you still using it, or did you abandon it and therefore not include it?

**Comment by BusinessDuck** [comment]
Hi! Thank you.

>What is the status, since you didnt include it in the description of this project?

Suspended now, but the Trend Line project will rewrited to `Pine Script` soon.
