### ISSUE TITLE
Request add StochasticRSI

### ISSUE THREAD

**Issue by nasa8x** [debut-js/Indicators#45]
Hi,

Can you add StochasticRSI indicator like technicalindicators? But the usage is the same as yours.

Thank you.

**Comment by BusinessDuck** [comment]
https://www.investopedia.com/terms/s/stochrsi.asp like this?

**Comment by nasa8x** [comment]
> https://www.investopedia.com/terms/s/stochrsi.asp like this?

That's right.

**Comment by BusinessDuck** [comment]
Stoch RSI has been added to indicators list in [1.3.20 release](https://github.com/debut-js/Indicators/releases/tag/v1.3.20), please test it and let me know

**Comment by nasa8x** [comment]
So fast, so great.
Thank you very much.
