### ISSUE TITLE
MFI indicator

### ISSUE THREAD

**Issue by angryrobotdeals** [debut-js/Indicators#46]
#### Description

Your library currently lacks the Money Flow Index (MFI) indicator, which is a standard indicator available on the Metatrader platform.

The Money Flow Index (MFI) is a technical oscillator that uses price and volume data to identify overbought or oversold signals in an asset. It can also be used to spot divergences that warn of a trend change in price. The oscillator moves between 0 and 100.

#### Request

It would be greatly appreciated if you could include the MFI indicator in your library. This addition would enhance the functionality and provide users with a valuable tool for technical analysis.

Thank you for considering this request.

**Comment by Podolchak** [comment]
Long time choosing an indicator, finally found the perfect one, but there is no main thing for me :(

**Comment by BusinessDuck** [comment]
@Podolchak What is the main thing for you?
